#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

${SCRIPTPATH}/down &


# Change mouse acceleration
${SCRIPTPATH}/scripts/mouse-settings.sh &

# Create symlink for alacritty
ln -s ${SCRIPTPATH}/alacritty.yml ~/.config/alacritty/alacritty.yml &

# Create symlink for rofi
ln -s ${SCRIPTPATH}/rofi/theme/config2.rasi ~/.config/rofi/config.rasi &

# Create symlink for picom
ln -s ${SCRIPTPATH}/picom.conf ~/.config/picom/ &


#set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale "${SCRIPTPATH}/background.jpg"
fi

# extra utils to make this theme a little more homey
if [ -x "$(command -v dunst)" ]; then
  dunst -config ~/.config/dunst/dunstrc &
fi

#boot a polybar for each monitor
cd ${SCRIPTPATH}/polybar
polybar -m | sed s/:.*// | tac | while read -r monitor
do
  monitor=$monitor polybar -c config.ini main &> /tmp/polybar.log &
done

#boot compton or picom if it exists
if [ -x "$(command -v picom)" ]; then
  picom &> /dev/null &
fi
